# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish to NPM

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm

      - name: Cache node_modules
        id: cache-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: 16.x-${{ runner.OS }}-build-${{ hashFiles('package.json') }}

      - name: Setup Nodejs 16
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: npm install

      - name: Set variables
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Publish packages
        run: |
          lerna publish from-package --yes --message '🔖 chore: release version ${{ steps.vars.outputs.tag }}'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
