# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Matrix Testing

on:
  push:
    branches:
      - main
      - sandbox

  pull_request:
    branches:
      - main
      - sandbox

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["14", "16", "17"]
    name: Node ${{ matrix.node }} sample
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install NPM and run jest
        run: |
          npm install
          npm run test
